### ISSUE TITLE
sc_init interferes with MPI_Comm_create_group

### ISSUE THREAD

**Issue by jodlbauer** [cburstedde/p4est#30] opened 2018-01-15 13:56 UTC
When calling sc_init(...), the following mwe does not work (rank 0 is stuck when trying to create a group) using 3 or more ranks. Without the call to sc_init it works as expected, i.e. terminates without errors. The problem does not appear in version 1.1.

Line 1259ff in [sc_init](https://github.com/cburstedde/libsc/blob/f2c88cf80ca9dfc5038f0ac26a01d5015305dca2/src/sc.c#L1259) seem to cause the problem, i.e. it works when removing lines 1259-71.

[mwe_sc_group.txt](https://github.com/cburstedde/p4est/files/1631810/mwe_sc_group.txt)

**Comment by cburstedde** [comment] 2018-04-09 16:12
Would you have a workaround that fixes these lines of code, or would you rather say they are broken in general? Do you have a specific use case / supposed reason the code hangs?

**Comment by cburstedde** [comment] 2018-06-15 17:31
I have pushed the branch fix-init-node-comm. The interrference should be gone.
Now sc_init no longer calls any special communicator functions!
If you still need it, call it by hand as in test_node_comm.c.
Please let me know if/how this works for y'all.

**Comment by cburstedde** [comment] 2018-06-15 18:14
That branch refers to libsc. Use develop branch in p4est for testing. Will update/merge if successful.

**Comment by cburstedde** [comment] 2018-09-05 17:30
Hi, are there any news on testing the p4est develop with libsc fix-init-node-comm branches?
I'd hope the issue is fixed there.

**Comment by cburstedde** [comment] 2019-02-24 16:32
This is addressed in the versions 2.8+, which are preparing for v3.
It won't be fixed in branches up to 2.5 for backwards compatibility.
Please use the branch prev3-develop (both in p4est and sc) to use the fixed code.
Thanks a lot for the report!

**Closed by cburstedde** 2019-02-24 16:32 UTC
Labels: bug

**Comment by masterleinad** [comment] 2019-02-24 18:16
> This is addressed in the versions 2.8+, which are preparing for v3.
> It won't be fixed in branches up to 2.5 for backwards compatibility.

The latest release I could find is v2.2...

**Comment by cburstedde** [comment] 2019-02-24 20:04
> > This is addressed in the versions 2.8+, which are preparing for v3.
> > It won't be fixed in branches up to 2.5 for backwards compatibility.
> 
> The latest release I could find is v2.2...

Ah yes it's not tagged yet.  Try branch prev3-develop.
