### ISSUE TITLE
Build fail  without jansson

### ISSUE THREAD

**Issue by mkirilin** [cburstedde/p4est#227] opened 2023-08-15 17:16 UTC
**Description**
Build with cmkae fails on a system without jansson library.

**To Reproduce**
1. p4est repository is on  2e44 commit. sc repository is on 83bd.
2. Configure and build sc in debug mode and with mpi.
3. Configure and build p4est in debug and with mpi.

p4est configure output: `-- Could NOT find jansson (missing: jansson_DIR)`
p4est build output: 

```
/opt/software/easybuild/software/binutils/2.38-GCCcore-11.3.0/bin/ld: ../local/lib/libsc.a(sc_options.c.o): in function `sc_options_json_lookup':
sc_options.c:(.text+0x95): undefined reference to `json_object_get'
/opt/software/easybuild/software/binutils/2.38-GCCcore-11.3.0/bin/ld: sc_options.c:(.text+0x105): undefined reference to `json_object_get'
```
etc...

**Comment by pkestene** [comment] 2023-08-16 09:12
Hi @mkirilin 

Could you provide the full commit hash (at least first 7 characters) because I was not able to identify 2e44 in p4est repository, while I found 83bd019 in libsc (current master) ?

I tried to build both current p4est develop branch and master branch on a system where libjansson is not available; I didn't encounter any problem, it builds fine.

**Comment by mkirilin** [comment] 2023-08-16 13:50
Hi @pkestene 

the relevant commit is on eb24772a.
Some more details: compiler version is GCC 11.3.0. CMake version is 3.23.1 compiled with GCC 11.3.0.

**Comment by pkestene** [comment] 2023-08-16 16:17
@mkirilin 
Please re-check on your side.

eb24772 is current master of p4est.
This commit builds fine for me.

Make sure that libsc submodule is up-to-date inside your p4est clone (it should be on master too).

**Comment by mkirilin** [comment] 2023-08-18 15:02
@pkestene 
I double checked current commit states: both p4est and sc are on master.

The problem appears when jansson is not found via find_package() but is found via PkgConfig:
```
-- Could NOT find jansson (missing: jansson_DIR)
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- jansson library found via pkg-config
```

**Comment by pkestene** [comment] 2023-08-20 06:55
@mkirilin 

Ok. I understand now and I can reproduce. This is a bug.
I'll push a fix shortly.

**Comment by pkestene** [comment] 2023-08-20 07:46
@mkirilin 

you can try this branch : https://github.com/pkestene/p4est/tree/fix/jansson-pkgconfig for cross-checking

**Comment by mkirilin** [comment] 2023-08-21 09:49
@pkestene 
With p4est HEAD on 31aeaf206256ad4379729abde59e4f3dd62dc4c8 and libsc on both cburstedde/libsc@f622a4c052c6c7428ee2be82024cd8ae8ec3d283 and cburstedde/libsc@116a91b62d23ccb383880e662075471510ecd5c5  the problem persists.

**Comment by pkestene** [comment] 2023-08-21 10:26
@mkirilin I'm really sorry for the trouble
I made a silly copy paste error while working on a working branch; thanks for being persevering

https://github.com/cburstedde/p4est/blob/develop/cmake/jansson.cmake#L24 and https://github.com/cburstedde/p4est/blob/develop/cmake/jansson.cmake#L25 should use prefix P4EST and not LIBSC

@cburstedde would you prefer cancelling PR #229 and re-open a new PR (I've updated my fork with the new fix), or consider an additional PR ? sorry about that silly mistake.

**Comment by cburstedde** [comment] 2023-08-24 12:45
No worries @pkestener, thanks for your contributions! We have already merged PR #229. You may start a new PR no problem.

**Comment by cburstedde** [comment] 2023-08-24 12:46
> @pkestene With p4est HEAD on [31aeaf2](https://github.com/cburstedde/p4est/commit/31aeaf206256ad4379729abde59e4f3dd62dc4c8) and libsc on both [cburstedde/libsc@f622a4c](https://github.com/cburstedde/libsc/commit/f622a4c052c6c7428ee2be82024cd8ae8ec3d283) and [cburstedde/libsc@116a91b](https://github.com/cburstedde/libsc/commit/116a91b62d23ccb383880e662075471510ecd5c5) the problem persists.

Thanks for double-checking!

**Comment by mkirilin** [comment] 2023-08-25 09:06
Thanks for the fix. It builds well now on my machine.

**Closed** 2023-08-25 11:39 UTC
Labels: bug, investigate
